[MOD] 상세페이지 / 보관함으로 뒤로가기 및 코스 삭제 시 애니메이션 통일
Runnect/Runnect-Android pull request #277
Opened 2023-11-09 01:58 UTC by unam98

## 📌 개요

closed #253
## ✨ 작업 내용

- 보관함으로 뒤로가기 및 코스 삭제 시 애니메이션 통일

2023-11-09 15:59 UTC, leeeha requested changes

2023-11-09 15:59 UTC, leeeha commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        }
반복되는 코드를 함수화 하는 게 어떨까요??

```kotlin
finish()
overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)
```

2023-11-09 15:59 UTC, leeeha commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        onBackPressedDispatcher.addCallback(this, backPressedCallback)
코드 스타일의 차이일 수 있지만, 아래처럼 관련있는 코드를 함수로 묶어두면 나중에 볼 때 편하더라구요! 

```kotlin
private fun registerBackPressedCallback() { // 이 함수를 addObserver에서 호출 
  val callback = object : OnBackPressedCallback(true) {
    override fun handleOnBackPressed() {
      naviagteToPreviousScreen() 
    }
  }
  onBackPressedDispatcher.addCallback(this, callback)
}

private fun naviagteToPreviousScreen() {
  finish()
  overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)
}
```

2023-11-10 05:50 UTC, unam98 commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        }
좋은 의견입니다! 우선 여기 파일 내에서만 함수화해보고 프로젝트 전체적으로도 많이 쓰는 것 같다 싶으면 확장함수로 빼는 것도 괜찮을 것 같네요

2023-11-10 05:55 UTC, unam98 commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        onBackPressedDispatcher.addCallback(this, backPressedCallback)
finishViewAnimLeftRight()라는 네이밍으로 함수를 만들었는데 혹시 위의 코드에서 알려주신 navigateToPreviousScreen()이라는 함수가 다른 파일에서 쓰이고 있는 것인가요? 그렇다면 이름을 navigateToPreviousScreen()으로 맞추겠습니다

2023-11-11 13:10 UTC, leeeha commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        }
다른 부분에서도 저 코드가 반복되는 경우가 많더라구요!! 확장함수로 만드는 거 좋은 거 같아요!

2023-11-11 13:12 UTC, leeeha commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        onBackPressedDispatcher.addCallback(this, backPressedCallback)
저는 다른 코드에서 navigateToPreviousScreen 이라는 함수명을 사용하긴 했습니다! 
현재 액티비티에서 뒤로가기 버튼을 누르면 이전 액티비티로 돌아간다는 걸 표현하고 싶어서 그렇게 작성했던 걸로 기억합니다!

2023-11-11 13:17 UTC, leeeha approved these changes

2023-11-11 13:17 UTC, leeeha commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        onBackPressedDispatcher.addCallback(this, backPressedCallback)
addObserver 함수에서 onBackPressedDispatcher에 콜백 등록하는 코드도 
registerBackPressedCallback 이라는 함수를 따로 만들어서 그 안에서 작성하는 게 어떨까 싶습니다! 

backPressedCallback 이라는 변수를 굳이 전역 변수로 만들 필요가 없을 거 같아서요!

2023-11-14 02:00 UTC, unam98 commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        onBackPressedDispatcher.addCallback(this, backPressedCallback)
반영했습니다!

2023-11-14 02:06 UTC, unam98 commented on app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
> +        }
확장함수로 만들었고 반영했습니다!

2023-11-14 02:06 UTC, merged