[FEAT] 코스 그리기 / 코스 제목 입력 후 키보드 내리기
Runnect/Runnect-Android pull request #279
Opened 2023-11-09 05:33 UTC by unam98

## 📌 개요

closed #277
## ✨ 작업 내용

- 코스 제목 입력 후 완성하기 버튼 누르면 키보드 내리기
## ✨ PR 포인트

말씀해주셨던 동작이 아래 영상과 같을까요? 다르다면 알려주세요! 반영하겠습니다!

## 📸 스크린샷/동영상

https://github.com/Runnect/Runnect-Android/assets/89737271/48589625-fd34-4a78-a2cc-5222bc5c1d95

2023-11-09 16:05 UTC, leeeha requested changes

2023-11-09 16:05 UTC, leeeha commented on app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
> +
기존에 구현되어 있는 hideKeyboard 라는 확장 함수 이용하면 더 좋을 거 같습니다! 

그리고 실행 결과 보니까 키보드 뿐만 아니라 바텀 시트 자체가 dismiss 되는 게 좋을 거 같아요!

2023-11-10 06:07 UTC, unam98 commented on app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
> +
넵! 말씀해주신 두 항목 다 반영해서 커밋 올렸습니다!

2023-11-11 13:17 UTC, leeeha approved these changes

2023-11-12 09:56 UTC, merged